package com.example.myapplication.item

data class Nutrition (val startTime: Long,
                      val calories: Double,
                      val totalFat: Double,
                      val saturatedFat: Double,
                      val transFat: Double,
                      val dietaryFiber: Double,
                      val sugar: Double,
                      val protein: Double,
                      val cholesterol: Double,
                      val sodium: Double,
                      val vitaminA: Double,
                      val vitaminC: Double,
                      val vitaminD: Double,
                      val calcium: Double,
                      val iron: Double,
                      val unsaturatedFat: Double?,
                      val polyunsaturatedFat: Double?,
                      val monounsaturatedFat: Double?,
                      val copper: Double?,
                      val folicAcid: Double?,
                      val iodine: Double?,
                      val magnesium: Double?,
                      val niacin: Double?,
                      val pantothenicAcid: Double?,
                      val phosphorus: Double?,
                      val riboflavin: Double?,
                      val thiamin: Double?,
                      val vitaminB12: Double?,
                      val vitaminB6: Double?,
                      val vitaminE: Double?,
                      val zinc: Double?,
                      val chloride: Double?,
                      val chromium: Double?,
                      val folate: Double?,
                      val manganese: Double?,
                      val molybdenum: Double?,
                      val selenium: Double?,
                      val vitaminK: Double?,
                      val pkgName: String): HealthData()  {



}